swagger: "2.0"
host:
 - "^api\\.uber\\.com$"
 - "localhost:8080"
basePath: "\/v1"
produces:
- application/json
consumes:
- application/json
schemes:
- https
paths:
  namingConvention: "spine-case"
  components:
    0: resource
    1: sub-resource
  operationId:
    namingConvention: "camelCase"
  tags:
    namingConvention: "ProperCase"
  verbs: "get"
    # post, patch, put, delete
    #- get
  parameters:
    query:
      namingConvention: "snake_case"
      items:
        - name: limit
          schemaRef: "#/parameters/LimitParam"
        - name: offset
          schemaRef: "#/parameters/OffsetParam"
    header:
      namingConvention: "CAP-SPINE-CASE"
    path:
      namingConvention: "snake_case"
  status:
    200:
    default:
      schemaRef: "#/definitions/Error"
  schema:
    properties:
      - name: "^.*\\_?id"
        format: uuid
      - name: "image"
        format: uuid
      - name: "currency_code"
        format: currency
        schemaRef: "#/definitions/CurrencyCode"
      - name: "^.*\\_?uuid"
        format: uuid
      - name: "^.*\\_?email"
        format: email
